Feature 17 get boyler types by
lmalvasia/CaldAR pull request #9
Opened 2020-11-22 19:04 UTC by pabloise

2020-11-22 21:41 UTC, lmalvasia requested changes

2020-11-22 21:41 UTC, lmalvasia commented on src/controllers/boylerTypesController.js
> +const boylerTypesByDescription = require('../data/boylerTypes.json');
This line it's not necessary. You have to use the const boylerTypes that you defined above.

2020-11-22 21:41 UTC, lmalvasia commented on src/controllers/boylerTypesController.js
> +module.exports = {
You should have one module.exports per file. If you have to export more than one thing, you will have something like:
```
module.exports = {
    getAllBoylerTypes,
   getBoylerTypesByDescription
};
```

2020-11-22 21:41 UTC, lmalvasia commented on src/controllers/boylerTypesController.js
> +const getBoylerTypesByDescription = () => boylerTypesByDescription;
You have to make a filter based on the boylerTypes const defined above. For example:
```
const getBoylerTypesByDescription = description => {
  const boylerTypesByDescription = boylerTypes.filter(boylerType => {
     // logic for filtering boylerTypes by description
  });
  return boylerTypesByDescription;
};
```

2020-11-22 21:41 UTC, lmalvasia commented on src/index.js
> +  const boylerTyperByDescription = boylerTypesController.getBoylerTypesByDescription();
You have to pass the req.params.description to the getBoylerTypesByDescription function
```const boylerTyperByDescription = boylerTypesController.getBoylerTypesByDescription(description);```

2020-11-22 21:41 UTC, lmalvasia commented on src/index.js
> +  res.send(req.params.description)
You should send the response from the `getBoylerTypesByDescription` function. 
```res.send(boylerTyperByDescription)```

2020-11-23 19:23 UTC, pabloise commented on src/index.js
> +  const boylerTyperByDescription = boylerTypesController.getBoylerTypesByDescription();
Done

2020-11-23 19:31 UTC, lmalvasia approved these changes

2020-11-23 19:32 UTC, merged